config/routes.rb
Rails.application.routes.draw do
resources :lists do
  resources :items, except: [:index]
end
root 'home#index'
resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user 
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :member }
  has_many :lists

  validates :name, length:{minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: {minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: { minimum: 3, maximum: 250}

  has_secure_password
  enum role: [:member, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def require_sign_in
    unless current_user
      flash[:alert] = "You must be signed in to do that"
      redirect_to new_session_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def show
    @item = Item.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @item = Item.new
  end

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)

    if @item.save
      flash[:notice] = "Item was added to list"
      redirect_to [@list]
    else
      flash.now[:alert] = "There was an error adding the item to the list. Please try again"
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(item_params)
    if @item.save
      flash[:notice] =  "New Item added"
      redirect_to [@item.list]
    else
      flash[:notice] = "There was an error saving the new item. Please try again."
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      flash[:notice] = "\"#{@item.title}\" was deleted."
      redirect_to @item.list
    else
      flash.now[:alert] = "There was an error deleting the item"
      render :index
    end
  end

  private
  def item_params
    params.require(:item).permit(:title, :amount, :completed)
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_sign_in
  before_action :authorize_user, except: [:index, :new, :create]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user

    if @list.save
      redirect_to @list, notice: "List was saved successfully."
    else
      flash.now[:alert] = "Error creating list. Please try again."
      render :new
    end
  end

  def edit
      @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.assign_attributes(list_params)

    if @list.save
       flash[:notice] = "list was updated."
      redirect_to @list
    else
      flash.now[:alert] = "Error saving list. Please try again."
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])

     if @list.destroy
       flash[:notice] = "\"#{@list.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the list."
       render :show
     end
   end

   private

   def list_params
     params.require(:list).permit(:name, :description, :public)
   end

   def authorize_user
     list = List.find(params[:id])

     unless current_user == list.user || current_user.admin?
       flash[:alert] = "You must be an admin to do that."
       redirect_to lists_path
     end
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      create_session(user)
      flash[:notice] = "Welcome, #{user.name}!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
        flash[:notice] = "Welcome to Grocery List #{@user.name}!"
        create_session(@user)
        redirect_to root_path
    else
      flash.now[:alert] = "There was an error in the sign up proccess. Please try again"
      render
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
# #5
     content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/lists_helper.rb
module ListsHelper
  def user_is_authorized_for_lists?
    current_user && (current_user == list.user || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
     session[:user_id] = user.id
   end

   def destroy_session(user)
     session[:user_id] = nil
   end
 
   def current_user
     User.find_by(id: session[:user_id])
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">

  <div class="jumbotron">
     <h3>Come on and sign up here!</h3>
     <p></p>
     <p>
       <%= link_to "Sign In", new_session_path %> or
       <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
     </p>
   </div>
</div>

app/views/items/edit.html.erb
<div class="container">
  <h1>Edit Item</h1>
  <div class="col-md-8">
    <%= form_for [@item.list, @item] do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title  %>

      <%= f.label :amount %>
      <%= f.text_field :amount%>
      
      <%= f.label :completed %>
      <%= f.check_box :completed %>

      <%= f.submit "Save changes"%>
      <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>Add Item</h1>
  <div class="col-md-8">
<%= form_for [@list, @item] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title  %>

  <%= f.label :amount %>
  <%= f.text_field :amount%>

  <%= f.label :completed %>
  <%= f.check_box :completed%>

  <%= f.submit "Add to list"%>
 <% end %>

</div>

app/views/items/show.html.erb
<div class="container">


    <h1>Edit Item</h1>
    <div class="col-md-8">
      <%= form_for [@item.list, @item] do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :amount %>
        <%= f.text_field :amount%>

        <%= f.label :completed %>
        <%= f.check_box :completed %>

        <%= f.submit "Save changes"%>
        <% end %>
    </div>

  <div class="col-md-4">
    <%= link_to "Edit", edit_list_item_path(@item.list, @item), class: 'btn btn-success' %>
    <%= link_to "Delete Item", [@item.list, @item], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Item?' } %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grocery List</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="background">
    <img src="http://drive.google.com/uc?export=view&id=11KHb3u1wqD0psZQn92g7bYJyw0m6fu9d" class="stretch" alt="" />
    </div>
    <div class="container">
      <ul class="nav nav-tabs">
        <%= link_to "Home", root_path, class:'btn btn-primary'%>
        <%= link_to "Lists", lists_path, class: 'btn btn-primary'%>
        <% if current_user %>
          <li class="pull-right"><%= link_to "#{current_user.name} -Sign Out", session_path(current_user), method: :delete %></li>
        <% else %>
          <li class="pull-right"><%= link_to "Sign In", new_session_path %></li>
          <li class="pull-right"><%= link_to "Sign Up", new_user_path %></li>
        <% end %>

      </ul>
        <div class="jumbotron text-center">
          <h1>Groceries<h1>
            <p>Welcome to the list</p>
        </div>

      </div>

      <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
    <%= yield %>


  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
  
<h1>Edit List</h1>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter list description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public list
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>
</div>

app/views/lists/index.html.erb
<div class="container">

<h1>Lists</h1>

  <%= link_to "New List", new_list_path, class: 'btn btn-success' %>

 <div class="row">
   <div class="col-md-8">
     <% @lists.each do |list| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to list.name, list %>
           </h4>
           <small>
             <%= list.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>

 </div>
 </div>

app/views/lists/new.html.erb
<div class="container">

  <h1>New List</h1>

   <div class="row">
     <div class="col-md-8">
       <%= form_for @list do |f| %>
         <div class="form-group">
           <%= f.label :name %>
           <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
         </div>
         <div class="form-group">
           <%= f.label :description %>
           <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter list description" %>
         </div>
         <div class="form-group">
           <%= f.label :public, class: 'checkbox' do %>
             <%= f.check_box :public %> Public list
           <% end %>
         </div>
         <%= f.submit "Save", class: 'btn btn-success' %>
       <% end %>
     </div>
   </div>
 </div>

app/views/lists/show.html.erb
<div class="container">

  <h1><%= @list.name %></h1>

   <%= link_to "Edit List", edit_list_path, class: 'btn btn-success' %>

   <div class="row">
     <div class="col-md-8">
       <p class="lead"><%= @list.description %></p>
       <table class="table table-hover table-bordered">
         <thead>
           <tr>
             <th>Title</th>
             <th>Quantity</th>
             <th>In the cart</th>
           </tr>
         </thead>
         <tbody>
           <% @list.items.each do |item| %>
             <tr>
               <td>
                 <strong>
                   <% if current_user %>
                   <p><%= link_to item.title, list_item_path(@list, item) %></p>
                   <% end %>
                 </strong>
               </td>
               <td class="text-info">
                 <%= item.amount %>
               </td>
               <td class="check_box">
                 <%= item.completed %>
               </td>
             </tr>
             <% end %>
         </tbody>
       </table>
       <% if current_user %>
       <%= link_to "New Item", new_list_item_path(@list), class: 'btn btn-success' %>
       <%= link_to "Delete list", @list, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this list?' } %>
       <% end %>
      </div>
     </div>
     </div>

   </div>
 </div>

app/views/users/new.html.erb
<div class="container">

  <h2>Sign up</h2>

  <div class="row">
    <div class="col-md-8">
      <%= form_for @user do |f|%>
        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@user.errors.count, "error") %></h4>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li><% msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_group_tag(@user.errors[:name]) do %>
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
          <% end %>
          <%= form_group_tag(@user.errors[:email]) do %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
          <% end %>
          <%= form_group_tag(@user.errors[:password]) do %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
          <% end %>
          <%= form_group_tag(@user.errors[:password_confirmation]) do %>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
          <% end %>
          <div class="form-group">
            <%= f.submit "Sign up", class: 'btn btn-success' %>
          </div>
        <% end %>

    </div>
  </div>
</div>